---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: subsonic
spec:
  targetNamespaces:
  - subsonic

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: subsonic-mariadb-operator
  namespace: subsonic
spec:
  channel: alpha
  name: mariadb-operator-app
  source: operatorhubio-catalog
  sourceNamespace: olm

---
apiVersion: mariadb.persistentsys/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: subsonic
spec:
  database: subsonic
  username: root
  password: password
  rootpwd: password
  size: 1
  image: 'mariadb/server:10.4'

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: subsonic
spec:
  selector:
    MariaDB_cr: mariadb
    app: MariaDB
    tier: mariadb
  ports:
  - name: dbport
    port: 3306
    targetPort: 3306
