---
apiVersion: mariadb.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: subsonic
spec:
  masters: 1
  replicas: 0
  mariadb_database_name: subsonic
  mariadb_user: db_user
  mariadb_image: mariadb:10.4
  mariadb_password: password
  mariadb_pvc_storage_request: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: subsonic
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
