---
apiVersion: mariadb.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: subsonic
spec:
  masters: 1
  replicas: 0
  mariadb_database_name: subsonic
  mariadb_user: db_user
  mariadb_image: mariadb:10.4
  mariadb_password: password
  mariadb_root_password: password
  mariadb_pvc_storage_request: 1Gi
