apiVersion: v1
kind: Service
metadata:
  name: subsonic
  labels:
    run: subsonic
  annotations:
    external-dns.alpha.kubernetes.io/hostname: subsonick8s.cluster.local
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: subsonic
  loadBalancerIP: 193.1.1.3
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress-subsonic
spec:
  rules:
  - host: subsonick8s.cluster.local
    http:
      paths:
      - backend:
          serviceName: subsonic
          servicePort: 80
