---
apiVersion: v1
kind: Namespace
metadata:
  name: subsonic
  labels:
    name: subsonic

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: subsonic-music-data-claim
  namespace: subsonic
spec:
  storageClassName: mp3-directory
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 300Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: subsonic
spec:
  storageClassName: mariadb-subsonic-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subsonic
  name: subsonic
  namespace: subsonic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subsonic
  template:
    metadata:
      labels:
        app: subsonic
    spec:
      initContainers:
      - name: database-setup
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        command: [sh,-c,mysql -h mariadb-service -ppassword -e "CREATE DATABASE IF NOT EXISTS subsonic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; GRANT ALL PRIVILEGES ON subsonic.* TO 'root'@'%' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"]
      containers:
      - image: rwlove/subsonic:6.1.6
        imagePullPolicy: IfNotPresent
        name: subsonic
        env:
        - name: SUBSONIC_DB
          value: "jdbc:mysql://mariadb-service:3306/subsonic?user=root&password=password&characterEncoding=UTF-8"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: music-volume
          mountPath: /music
          readOnly: true
        - name: data-volume
          mountPath: /data
        - name: playlist-volume
          mountPath: /playlists
        - name: podcast-volume
          mountPath: /podcasts          
      volumes:
      - name: music-volume
        persistentVolumeClaim:
          claimName: subsonic-music-data-claim
      - name: data-volume
        nfs:
          server: brain.thesteamedcrab.com
          path: /mnt/mass_storage/docker_storage/subsonick8s/data
      - name: playlist-volume
        nfs:
          server: brain.thesteamedcrab.com
          path: /mnt/mass_storage/docker_storage/subsonick8s/playlists
      - name: podcast-volume
        nfs:
          server: brain.thesteamedcrab.com
          path: /mnt/mass_storage/docker_storage/subsonick8s/podcasts

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: subsonic
spec:
  targetNamespaces:
  - subsonic

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: subsonic-mariadb-operator
  namespace: subsonic
spec:
  channel: alpha
  name: mariadb-operator-app
  source: operatorhubio-catalog
  sourceNamespace: olm

---
apiVersion: mariadb.persistentsys/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: subsonic
spec:
  database: subsonic
  username: root
  password: password
  rootpwd: password
  size: 1
  image: 'mariadb/server:10.4'

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: subsonic
spec:
  selector:
    MariaDB_cr: mariadb
    app: MariaDB
    tier: mariadb
  ports:
  - name: dbport
    port: 3306
    targetPort: 3306
