apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    run: homeassistant
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homeassistantk8s.thesteamedcrab.com
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: homeassistant
  loadBalancerIP: 192.168.6.5
