apiVersion: v1
kind: Service
metadata:
  name: mpd
  namespace: mpd
  labels:
    run: mpd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mpd.thesteamedcrab.com
spec:
  type: LoadBalancer
  ports:
  - name: sixthousandsixhundred
    port: 6600
    targetPort: 6600
  - name: eightthousandeighthundred
    port: 8800
    targetPort: 8800  
  selector:
    app: mpd
  loadBalancerIP: 192.168.6.7
