apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    run: pihole
  annotations:
    external-dns.alpha.kubernetes.io/hostname: piholek8s.thesteamedcrab.com
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pihole
  loadBalancerIP: 192.168.6.4
