apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    run: pihole
  annotations:
    external-dns.alpha.kubernetes.io/hostname: piholek8s.cluster.local
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pihole
  loadBalancerIP: 192.168.6.4
---          
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress-pihole
spec:
  rules:          
  - host: piholek8s.cluster.local
    http:
      paths:
      - backend:
          serviceName: pihole
          servicePort: 80
