---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    run: pihole
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: tcp
    targetPort: 443
  - name: fiftythree
    port: 53
    targetPort: 53
  - name: sixtyseven
    port: 67
    protocol: udp
    targetPort: 67
  selector:
    app: pihole
  loadBalancerIP: 192.168.6.4
