---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-pv-claim
  namespace: sonarr
spec:
  storageClassName: qbittorrentvpn-data-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
