---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mythtv-backend-mysql-pv-claim
  namespace: mythtv
spec:
  storageClassName: mythtv-backend-mysql-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: mythtv
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: mythtv-backend
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mythtv-backend-mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mythtv
spec:
  ports:
  - name: dbport
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
