---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data-pv-claim
  namespace: lidarr
spec:
  storageClassName: qbittorrentvpn-lidarr-data-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
