---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-music
  labels:
    type: local
spec:
  storageClassName: airsonic-music-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/storage/MP3s

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-playlists
  labels:
    type: local
spec:
  storageClassName: airsonic-playlists-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/airsonic/playlists

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-podcasts
  labels:
    type: local
spec:
  storageClassName: airsonic-podcasts-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/airsonic/podcasts


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airsonic-config
  labels:
    type: local
spec:
  storageClassName: airsonic-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/airsonic/config
