---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flood-data
  labels:
    type: local
spec:
  storageClassName: flood-data-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/flood/data
