apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-music-data
  labels:
    type: local
spec:
  storageClassName: gonic-music-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/storage/MP3s

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-podcasts-data
  labels:
    type: local
spec:
  storageClassName: gonic-podcasts-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/gonic/podcasts
