---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grocy-volume
  labels:
    type: local
spec:
  storageClassName: grocy-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/grocy
