---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-jellyfin-data
  labels:
    type: local
spec:
  storageClassName: jellyfin-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: vmheart.thesteamedcrab.com
    path: /mnt/sda/delme_qbt/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  labels:
    type: local
spec:
  storageClassName: jellyfin-media-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/storage/video/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  labels:
    type: local
spec:
  storageClassName: jellyfin-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/jellyfin/config
