---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-lidarr-data
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-lidarr-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: vmheart.thesteamedcrab.com
    path: /mnt/sda/k8s_qbittorrent_downloads

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-media
  labels:
    type: local
spec:
  storageClassName: lidarr-media-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/storage/MP3s/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-config
  labels:
    type: local
spec:
  storageClassName: lidarr-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/lidarr/config
