---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mariadb-subsonic-pv-volume
  labels:
    type: local
spec:
  storageClassName: mariadb-subsonic-storage-class
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/mariadb/subsonic
