---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mythtv-backend-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: mythtv-backend-mysql-storage-class
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/mariadb/mythtv-backend
