---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-config
  labels:
    type: local
spec:
  storageClassName: overseerr-config-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/overseerr/config
