---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-storage-volume
  labels:
    type: local
spec:
  storageClassName: pihole-storage-class
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/pihole
