---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-data
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/qbittorrentvpn/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-config
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/qbittorrentvpn/config
