---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-data
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: vmheart.thesteamedcrab.com
    path: /mnt/sda/k8s_qbittorrent_downloads/

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-config
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: vmheart.thesteamedcrab.com
    path: /mnt/sda/delme_qbt/config
