---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-data
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-radarr-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: vmheart.thesteamedcrab.com
    path: /mnt/sda/delme_qbt/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media
  labels:
    type: local
spec:
  storageClassName: radarr-media-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/radarr/media

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
  labels:
    type: local
spec:
  storageClassName: radarr-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/radarr/config
