---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rsyslog-data
  labels:
    type: local
spec:
  storageClassName: rsyslog-data-storage-class
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/rsyslog
