---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrentvpn-data
  labels:
    type: local
spec:
  storageClassName: qbittorrentvpn-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: vmheart.thesteamedcrab.com
    path: /mnt/sda/delme_qbt/data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media
  labels:
    type: local
spec:
  storageClassName: sonarr-media-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/sonarr/media

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
  labels:
    type: local
spec:
  storageClassName: sonarr-config-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/sonarr/config
