---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-data
  labels:
    type: local
spec:
  storageClassName: tekton-data-storage-class
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: brain.thesteamedcrab.com
    path: /mnt/mass_storage/kubernetes/tekton
