---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-webroot-claim
  namespace: nextcloud
spec:
  storageClassName: nextcloud-webroot-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-mariadb-0
  namespace: nextcloud
spec:
  storageClassName: mariadb-nextcloud-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: mariadb.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  masters: 1
  replicas: 0
  mariadb_password: password
  mariadb_image: mariadb:10.4
  mariadb_pvc_storage_request: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: nextcloud
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

mariadb-mariadb-0
