---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud

---
apiVersion: mariadb.persistentsys/v1alpha1
kind: MariaDB
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
spec:
  database: test-db
  username: nextcloud
  password: password
  rootpwd: password
  size: 1
  image: 'mariadb/server:10.4'