---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud

---
apiVersion: mariadb.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
spec:
  masters: 1
  replicas: 0
  mariadb_password: password
  mariadb_image: mariadb:10.4
  mariadb_pvc_storage_request: 1Gi
