---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    name: nextcloud

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mysql-pv-claim
  namespace: nextcloud
spec:
  storageClassName: nextcloud-mysql-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: nextcloud
type: Opaque
data:
  nextcloud-username: bmV4dGNsb3Vk
  nextcloud-password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
  namespace: nextcloud
type: Opaque
data:
  db-username: bmV4dGNsb3Vk
  db-password: cGFzc3dvcmQ=

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: nextcloud
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nextcloud-mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: nextcloud
spec:
  ports:
  - name: dbport
    port: 3306
    targetPort: 3306
  selector:
    app: mysql

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-webroot-claim
  namespace: nextcloud
spec:
  storageClassName: nextcloud-webroot-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
