---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rsyslog-pvc
  namespace: "rsyslog"
spec:
  storageClassName: rsyslog-data-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-deployment
  namespace: rsyslog
  labels:
    app: rsyslog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: sudheerc1190/rsyslog:latest
        ports:
        - containerPort: 514
        resources:
          requests:
            cpu: 250m
            memory: 524Mi
        volumeMounts:
          - name: rsyslog-volume
            mountPath: "/var/log"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rsyslog-volume
          persistentVolumeClaim:
            claimName: rsyslog-pvc
