---
apiVersion: v1
kind: Service
metadata:
  name: "rsyslog"
  namespace: "rsyslog"
  annotations:
spec:
  ports:
    - port: 514
      targetPort: 514
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.6.33
  selector:
    app: "rsyslog"
