apiVersion: v1
kind: Service
metadata:
  name: rompr
  namespace: mpd  
  labels:
    run: rompr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rompr.thesteamedcrab.com
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: romprsixthousandsixhundred
    port: 6600
    targetPort: 6600
  - name: romprsixthousandsixhundredeighty
    port: 6680
    targetPort: 6680
  selector:
    app: rompr
  loadBalancerIP: 192.168.6.8
