apiVersion: v1
kind: Service
metadata:
  name: rompr
  labels:
    run: rompr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rompr.thesteamedcrab.com
spec:
  type: LoadBalancer
  ports:
  - name: sixthousandsixhundred
    port: 6600
    targetPort: 6600
  - name: sixthousandsixhundredeighty
    port: 6680
    targetPort: 6680
  selector:
    app: rompr
  loadBalancerIP: 192.168.6.7
