apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: mariadb-operator
spec:
  targetNamespaces:
  - mariadb-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-mariadb-operator-app
  namespace: mariadb-operator
spec:
  channel: alpha
  name: mariadb-operator-app
  source: operatorhubio-catalog
  sourceNamespace: olm
