apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-redis-enterprise
  namespace: operators
spec:
  channel: alpha
  name: redis-enterprise
  source: operatorhubio-catalog
  sourceNamespace: olm