#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: linuxserver/airsonic
  pullPolicy: IfNotPresent
  tag: v10.6.2-ls97

strategy:
  type: Recreate

env:
  TZ: "America/New_York"
  PUID: 1000
  PGID: 1001
  # CONTEXT_PATH: "url-base" # Used to set the base path for reverse proxies eg. /booksonic, /books, etc.
  # JAVA_OPTS: "" # For passing additional java options. For some reverse proxies, you may need to pass JAVA_OPTS=-Dserver.use-forward-headers=true for airsonic to generate the proper URL schemes.


service:
  port:
    port: 4040
  type: LoadBalancer
  loadBalancerIP: 192.168.6.42

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
    storageClass: "airsonic-config-storage-class"
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false

  music:
    enabled: false
    emptyDir: false
    mountPath: /music
    storageClass: "airsonic-music-storage-class"
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false

  playlists:
    enabled: false
    emptyDir: false
    mountPath: /playlists
    storageClass: "airsonic-playlists-storage-class"
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false

  podcasts:
    enabled: true
    emptyDir: false
    mountPath: /podcasts
    storageClass: "airsonic-podcasts-storage-class"
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false

  media:
    enabled: false
    emptyDir: false
    mountPath: /media

# Prometheus Metrics
exportarr:
  enabled: false
  image:
    repository: onedr0p/exportarr
    tag: v0.3.0
    pullPolicy: IfNotPresent
  url: "http://airsonic.thesteamedcrab.com:4040"
  apikey:
  port: 9708
  serviceMonitor:
    enabled: false
    namespace: radarr
    path: /metrics
    interval: 4m
    scrapeTimeout: 90s
    additionalLabels: {}

nameOverride: "airsonic"
fullnameOverride: ""

timezone: 'America/New_York'
