#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: flaresolverr/flaresolverr
  pullPolicy: IfNotPresent
  tag: 2.1.0

strategy:
  type: Recreate

env:
  TZ: "America/New_York"
  PUID: 1000
  PGID: 1001
  # LOG_LEVEL: UTC

service:
  type: LoadBalancer
  port:
    port: 8191
  loadBalancerIP: 192.168.6.40
