#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: linuxserver/jellyfin
  pullPolicy: IfNotPresent
  tag: version-10.6.4-1

strategy:
  type: Recreate

env:
  TZ: "America/New_York"
  PUID: 1000
  PGID: 1001
  
service:
  type: LoadBalancer
  port:
    port: 8096
  loadBalancerIP: 192.168.6.41

persistence:
  config:
    enabled: true
    mountPath: /config
    storageClass: "jellyfin-config-storage-class"
    accessMode: ReadWriteOnce
    size: 1Gi

  media:
    enabled: true
    mountPath: /media
    storageClass: "jellyfin-media-storage-class"
    accessMode: ReadWriteOnce
    size: 1Gi
