#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: k8sathome/network-ups-tools
  tag: v2.7.4-2061-g46c7da76
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

env:
  TZ: 'America/New_York'

service:
  name: server
  type: LoadBalancer
  loadBalancerIP: 192.168.6.37
  port:
    port: 3493

# The main configuration files for network-ups-tools
config:
  # If set to 'values', the configuration will be read from these values.
  # Otherwise you have to mount a volume to /etc/nut containing the configuration files.
  mode: values

  # See https://github.com/networkupstools/nut/tree/master/conf for config sample files
  files:
    nut.conf: |
      MODE=netserver

    upsd.conf: |
      LISTEN 0.0.0.0

    ups.conf: |
      [apcupsd]
        driver = apcupsd-ups
        port = brain.thesteamedcrab.com:3551
        desc = "brain.thesteamedcrab.com apcupsd client"
