---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
type: Opaque
data:
  db-username: root
  db-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
type: Opaque
data:
  nextcloud-username: admin
  nextcloud-password: password
  NEXTCLOUD_TRUSTED_DOMAINS: thesteamedcrab.com
