image:
  repository: k8sathome/qbittorrent
  tag: v4.3.3
  pullPolicy: IfNotPresent

env:
  # Our qBittorrent image has a feature that can wait for the VPN to be connected before actually starting the application.
  # It does this by checking the contents of a file /shared/vpnstatus to contain the string 'connected'.
  WAIT_FOR_VPN: "true"

persistence:
  config:
    enabled: true
    mountPath: /config
    storageClass: qbittorrent-config-storage-class
    accessMode: ReadWriteOnce
    size: 1Gi
    subPath: ""
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  downloads:
    enabled: true
    storageClass: qbittorrent-downloads-storage-class
    accessMode: ReadWriteMany
    size: 10Gi
    subPath: ""
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  # This should be enabled so that both the qBittorrent and OpenVPN container have access to a shared volume mounted to /shared.
  # It will be used to communicate between the two containers.
  shared:
    enabled: true
    emptyDir: true  
    mountPath: /shared

addons:
  vpn:
    enabled: true
    # This Should be set to `openvpn`. This will set the add-on to use the default settings for OpenVPN based connections.
    type: openvpn

    openvpn:
    # If the podSecurityContext is set to run as a different user, make sure to run the OpenVPN container as root. 
    # This is required for it to be able to read certain configuration files. 
    securityContext:
      runAsGroup: 0
      runAsUser: 0
      capabilities:
        add:
        - NET_ADMIN

    env:
      # Set this environment variable to 'on' to make sure all traffic gets routed through the VPN container.
      # Make sure to check the other environment variables for the OpenVPN image to see how you can exclude certain
      # traffic from these firewall rules.
      FIREWALL: 'on'

    # The .ovpn file provided by your VPN provider goes here.
    #
    # Any CA / certificate must either be placed inline, or provided through an additionalVolumeMount so that OpenVPN can find it.
    #
    # Pay close attention to the last 3 lines in this file. They must be added if you wish to run a script when the connection
    # is opened / closed.
    configFile: |-
      remote ca.vpn.btguard.com 1194
      client
      dev tun
      proto udp
      daemon openvpn
      resolv-retry infinite
      nobind
      persist-key
      ca /config/openvpn/btguard.ca.crt
      verb 3
      mute 3
      auth-user-pass /config/openvpn/btguard.login.conf
      mute-replay-warnings
      float
      cipher AES-256-CBC
      auth SHA512
      fast-io
      pull
      
      script-security 2
      up /vpn/up.sh
      down /vpn/down.sh

    # The scripts that get run when the VPN connection opens/closes are defined here.
    # The default scripts will write a string to represent the current connection state to a file.
    # Our qBittorrent image has a feature that can wait for this file to contain the word 'connected' before actually starting the application.
    scripts:
      up: |-
        #!/bin/bash
        /etc/openvpn/up.sh
        echo "connected" > /shared/vpnstatus

      down: |-
        #!/bin/bash
        /etc/openvpn/down.sh
        echo "disconnected" > /shared/vpnstatus

service:
  type: LoadBalancer
  port:
    port: 8080
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  loadBalancerIP: 192.168.6.25
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster
