---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data-pv-claim
  namespace: radarr
spec:
  storageClassName: qbittorrentvpn-radarr-data-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
