apiVersion: v1
kind: Service
metadata:
  name: nginx-hello
  labels:
    run: nginx-hello
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx-hello.thesteamedcrab.com
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-hello
  loadBalancerIP: 192.168.6.2
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress-nginx-hello
spec:
  rules:
  - host: nginx-hello.thesteamedcrab.com
    http:
      paths:
      - backend:
          serviceName: nginx-hello
          servicePort: 80
